version: "3"
services:
  mysql-1:
    container_name: mysql-1
    build: ./docker/mysql
    image: mysqltest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  java-1:
    container_name: java-1
    build: ./docker/java
    image: springboot
    ports:
      - "18080:18080"
    depends_on:
      - mysql-1
    links:
      - mysql-1
    environment:
      MYSQL_IP: mysql-1
      MYSQL_PORT: 3306
      port: 18080
      password: root