version: "3"
services:
  mysql-1:
    container_name: mysql-1
    build: ./docker/mysql
    image: mysqltest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  java-1:
    container_name: java-1
    build: ./docker/java
    image: springboot
    ports:
      - "8082:8080"
    depends_on:
      - mysql-1
    links:
      - mysql-1
    environment:
      ip: mysql-1
      sqlport: 3307
      port: 8080